name: assignment
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyyaml
  - matplotlib
  - scipy
  - seaborn
  - scikit-learn
  - r-base
  - r-rrblup
  - rpy2